server:
  port: 8000

spring:
  data:
    redis:
      database: 3
      host: 127.0.0.1
      port: 6379
      password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/practice?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ikikyou
        login-password: 123456
        reset-enable: true
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

practice:
  #系统相关配置
  system:
    file:
      path: "/usr/local/files"
      size: 20
    #验证码校验方式
    captcha:
      type: math
    jwt:
      #jwt签名密钥
      signingKey: www.ikikyou.com
      #jwt过期时间（秒）默认当天有效
      expireTime: 36000
  #用户相关配置
  user:
    #删除用户时是否逻辑删除，默认为true
    isLogicalDelete: true

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        web: INFO
  charset:
    console: UTF-8
  config: classpath:logback-spring.xml

